let
    // 1. Conexão inicial para buscar as Listas do Quadro
    Fonte = Json.Document(
        Web.Contents(
            "https://api.trello.com",
            [
                RelativePath = "1/boards/SEU_QUADRO/lists",
                Query = [
                    key = "SUA_CHAVE",
                    token = "SEU_TOKEN"
                ]
            ]
        )
    ),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Listas Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"id","name"}, {"idList","NomeLista"}),

    // 2. Busca Dinâmica de Cards para cada Lista encontrada
    #"Buscar Cards" = Table.AddColumn(#"Listas Expandido", "Cards", each 
        Json.Document(
            Web.Contents(
                "https://api.trello.com",
                [
                    RelativePath = "1/lists/" & [idList] & "/cards",
                    Query = [key = "SUA_CHAVE", token = "SEU_TOKEN"]
                ]
            )
        )
    ),

    // 3. Expansão e Tratamento dos Cards
    #"Cards Expandido" = Table.ExpandListColumn(#"Buscar Cards", "Cards"),
    #"Cards Detalhado" = Table.ExpandRecordColumn(#"Cards Expandido", "Cards", 
        {"id", "name", "closed", "dateLastActivity", "due"}, 
        {"id_card_temp", "Nome_Card", "Arquivado", "Ultima_Atividade", "Data_Entrega"}),

    // 4. Integração com a Função Personalizada de Checklists
    #"Invocação Checklist" = Table.AddColumn(#"Cards Detalhado", "Checklist", each fn_Checklists_Card([id_card_temp], [Nome_Card])),
    #"Checklist Expandido" = Table.ExpandTableColumn(#"Invocação Checklist", "Checklist", 
        {"Item_Checklist", "Estado", "id_card"}, 
        {"Item_Checklist", "Estado", "id_card"}),

    // 5. Ajustes de Tipagem e Limpeza de Duplicatas
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Checklist Expandido", {
        {"Ultima_Atividade", type datetime}, 
        {"Data_Entrega", type datetime},
        {"NomeLista", type text},
        {"Nome_Card", type text}
    }),
    #"Filtro Final" = Table.Distinct(#"Tipo Alterado", {"id_card"})
in
    #"Filtro Final"
