let
    // Conexão com a API do Trello utilizando RelativePath para garantir atualização no Service
    Fonte = Json.Document(
        Web.Contents(
            "[https://api.trello.com](https://api.trello.com)",
            [
                RelativePath = "1/boards/SEU_QUADRO/cards",
                Query = [
                    key = "SUA_CHAVE",
                    token = "SEU_TOKEN"
                ]
            ]
        )
    ),

    // Conversão de JSON para Tabela e Expansão Inicial
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", 
        {"id", "closed", "dueComplete", "dateLastActivity", "desc", "due", "idBoard", "idList", "name"}, 
        {"id", "closed", "dueComplete", "dateLastActivity", "desc", "due", "idBoard", "idList", "name"}),

    // Tipagem dos Dados para garantir performance em cálculos DAX
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1 Expandido", {
        {"id", type text}, 
        {"closed", type logical}, 
        {"dueComplete", type logical}, 
        {"dateLastActivity", type datetime}, 
        {"desc", type text}, 
        {"due", type datetime}, 
        {"idBoard", type text}, 
        {"idList", type text}, 
        {"name", type text}
    }),

    // Invocação de Função Personalizada para granularidade de Checklists
    #"Função Personalizada Invocada" = Table.AddColumn(#"Tipo Alterado", "Checklists", each fn_Checklists_Card([id], [name])),
    
    // Ajuste Final de Nomenclatura para o Modelo Star Schema
    #"Colunas Renomeadas" = Table.RenameColumns(#"Função Personalizada Invocada",{{"id", "id_card"}})
in
    #"Colunas Renomeadas"


