let
    /* Conexão com a API do Trello - Extração de Cards
       Este script utiliza parâmetros para evitar problemas de privacidade e 
       facilitar a manutenção do pipeline de dados.
    */
    
    // Configurações de Acesso (Substitua pelos seus dados no Power BI local)
    BoardID = "SEU_QUADRO",
    APIKey = "SUA_CHAVE",
    APIToken = "SEU_TOKEN",

    Fonte = Json.Document(
        Web.Contents(
            "https://api.trello.com",
            [
                RelativePath = "1/boards/" & BoardID & "/cards",
                Query = [
                    key = APIKey,
                    token = APIToken
                ]
            ]
        )
    ),

    // Transformação Inicial
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    
    // Expansão seletiva dos campos do Trello
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", 
        {"id", "name", "idList", "due", "closed", "dateLastActivity", "desc"}, 
        {"id_card", "Nome_Card", "id_list", "Data_Entrega", "Arquivado", "Ultima_Atividade", "Descricao"}),

    // Invocação da função personalizada para buscar checklists vinculados
    // Nota: Certifique-se de que a função fn_Checklists_Card esteja criada no seu arquivo.
    #"Função Personalizada Invocada" = Table.AddColumn(#"Column1 Expandido", "Checklists", each fn_Checklists_Card([id_card], [Nome_Card])),

    // Tipagem dos dados
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Função Personalizada Invocada", {
        {"id_card", type text}, 
        {"Nome_Card", type text}, 
        {"id_list", type text}, 
        {"Data_Entrega", type datetime}, 
        {"Arquivado", type logical}, 
        {"Ultima_Atividade", type datetime}
    })
in
    #"Tipo Alterado"
